# Generated by Django 5.1.2 on 2024-10-14 18:58

import folio.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0002_alter_projects_technologies_alter_user_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=folio.fields.CustomTagsField(max_length=250),
        ),
    ]
